# Generated by Django 3.1.5 on 2021-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='profile_pics/background.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='profile'),
        ),
    ]
