# Generated by Django 3.1.5 on 2021-01-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_recentcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='profile_pics'),
        ),
    ]
