# Generated by Django 3.1.5 on 2021-01-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210112_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
