# Generated by Django 3.1.5 on 2021-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210112_1306'),
        ('users', '0008_profile_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hours',
        ),
        migrations.AddField(
            model_name='profile',
            name='applied_courses',
            field=models.ManyToManyField(blank=True, related_name='applied_courses', to='courses.Course'),
        ),
    ]
