# Generated by Django 3.1.5 on 2021-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default=' i am a freelancer i work from home', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=' my name is afenikhena favour i am a backend developer i love programmin the first day  i code it seems i have found my passion '),
            preserve_default=False,
        ),
    ]
