# Generated by Django 3.1.5 on 2021-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forumanswer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumquestion',
            options={'ordering': ['-timestamp']},
        ),
    ]
