# Generated by Django 3.1.5 on 2021-01-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210126_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumquestion',
            options={'ordering': ['-id']},
        ),
    ]
