# Generated by Django 3.1.5 on 2021-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210126_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
