# Generated by Django 3.1.5 on 2021-03-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.SlugField(max_length=20)),
                ('percent_off', models.IntegerField(default=0.1)),
                ('coupon_model', models.CharField(choices=[('Signal_Monthly', 'Signal_Monthly'), ('Quaterly_Monthly', 'Quaterly_Monthly'), ('Yearly_Monthly', 'Yearly_Monthly'), ('Academy_Monthly', 'Academy_Monthly')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
