# Generated by Django 3.1.5 on 2021-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.FloatField(default=0.1),
        ),
    ]
