# Generated by Django 3.1.5 on 2021-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_coupon', '0002_auto_20210324_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_model',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Signal_Monthly', 'Signal_Monthly'), ('Quaterly_Monthly', 'Quaterly_Monthly'), ('Yearly_Monthly', 'Yearly_Monthly'), ('Academy', 'Academy')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
