# Generated by Django 3.1.5 on 2021-03-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_coupon', '0003_auto_20210324_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Signal_Monthly', 'Signal_Monthly'), ('Signal_Quaterly', 'Signal_Quaterly'), ('Signal_Yearly', 'Signal_Yearly'), ('Academy', 'Academy')], max_length=20),
        ),
    ]
