# Generated by Django 3.1.5 on 2021-03-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_coupon', '0004_auto_20210324_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(max_length=20),
        ),
    ]
