# Generated by Django 3.1.5 on 2021-03-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_coupon', '0005_auto_20210324_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
