# Generated by Django 3.1.5 on 2021-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Free', max_length=30),
        ),
    ]
