# Generated by Django 3.1.5 on 2021-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20210111_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='discount',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
