# Generated by Django 3.1.5 on 2021-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20210406_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Beginner ', 'Beginner '), ('Intermediate ', 'Intermediate '), ('Advanced ', 'Advanced ')], default='Free', max_length=30),
        ),
    ]
