# Generated by Django 3.1.5 on 2021-04-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20210406_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
    ]
