# Generated by Django 3.1.5 on 2021-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20210412_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Beginner ', 'Beginner '), ('Intermediate ', 'Intermediate '), ('Advanced ', 'Advanced '), ('Ninja’s US30 Course', 'Ninja’s US30 Course')], default='Free', max_length=100),
        ),
    ]
