# Generated by Django 3.1.5 on 2021-01-19 01:07

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_quill.fields.QuillField(default='dfnvbkfvbf'),
            preserve_default=False,
        ),
    ]
