# Generated by Django 3.0.3 on 2020-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('ED', 'Education'), ('EN', 'Entertainment'), ('L', 'Lifestyle'), ('MT', 'Modern technology')], max_length=3, null=True),
        ),
    ]
