# Generated by Django 3.1.5 on 2021-01-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_action',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
