# Generated by Django 3.0.3 on 2020-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=362),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=362),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='image_height', null=True, upload_to='', width_field='image_width'),
        ),
    ]
