# Generated by Django 3.0.3 on 2020-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200530_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
