# Generated by Django 3.0.3 on 2020-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200606_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
