# Generated by Django 3.1.5 on 2021-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='aa.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
