# Generated by Django 3.1.5 on 2021-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210214_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('SPANISH', 'SPANISH')], default='English', max_length=20),
        ),
    ]
