# Generated by Django 3.1.5 on 2021-04-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
    ]
