# Generated by Django 3.1.5 on 2021-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_response',
            field=models.CharField(default='the', max_length=300),
            preserve_default=False,
        ),
    ]
