# Generated by Django 3.1.5 on 2021-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessages',
            name='duration',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
