# Generated by Django 3.1.5 on 2021-04-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_video_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_response',
            new_name='video_uri',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
