# Generated by Django 3.1.5 on 2021-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursemessages_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemessages',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='0:0', max_length=10),
        ),
    ]
