# Generated by Django 3.1.5 on 2021-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210113_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default='lesson_thumbnail/thumbnail.jpg', upload_to='lesson_thumbnail'),
        ),
    ]
