# Generated by Django 3.1.5 on 2021-01-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
