# Generated by Django 3.1.5 on 2021-01-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='view_count',
        ),
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
