# Generated by Django 3.1.5 on 2021-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-timestamp']},
        ),
    ]
