# Generated by Django 3.1.5 on 2021-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=80)),
                ('account_type', models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5')], max_length=10)),
                ('account_number', models.CharField(max_length=100)),
                ('slippage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('broker', models.CharField(max_length=100)),
                ('Broker_server', models.CharField(max_length=100)),
                ('choice_of_symbols', models.CharField(max_length=100)),
                ('forex_pairs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('indices', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('metals', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='CopyTradingSubscription',
        ),
    ]
