# Generated by Django 3.1.5 on 2021-02-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0003_auto_20210219_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradeinfo',
            name='discord_username',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
