# Generated by Django 3.1.5 on 2021-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(),
        ),
    ]
