# Generated by Django 3.1.5 on 2021-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20210130_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comming_soon', models.BooleanField(default=True)),
            ],
        ),
    ]
