# Generated by Django 3.1.5 on 2021-02-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_commingsoon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommingSoon',
            new_name='ComingSoon',
        ),
    ]
