# Generated by Django 3.1.5 on 2021-02-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20210222_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comingsoon',
            old_name='comming_soon',
            new_name='coming_soon',
        ),
    ]
