# Generated by Django 3.1.5 on 2021-04-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaltype',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='signaltype',
            name='price',
        ),
    ]
