# Generated by Django 3.1.5 on 2021-01-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignal',
            old_name='membership',
            new_name='signal_type',
        ),
    ]
