# Generated by Django 3.1.5 on 2021-01-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0002_auto_20210123_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signaltype',
            old_name='amount',
            new_name='price',
        ),
    ]
