# Generated by Django 3.1.5 on 2021-01-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0003_auto_20210123_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='stripe_plan_id',
            field=models.CharField(default='price_1ICusiAS6n0shLOqnp8R8mec', max_length=40),
            preserve_default=False,
        ),
    ]
