# Generated by Django 3.1.5 on 2021-01-25 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signal_app', '0004_signaltype_stripe_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignalSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField()),
                ('expiring_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('signal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signal_app.signaltype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSignal',
        ),
    ]
