# Generated by Django 3.1.5 on 2021-01-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0005_auto_20210125_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignalsubscription',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='usersignalsubscription',
            name='expiring_date',
        ),
    ]
